/* Fridge Assistant panel — translations + label maps.
 *
 * i18n: everything follows a simple rule — Dutch if Home Assistant's
 * (per-user) language is Dutch, English for anything else. See `_lang()`/`t()`
 * in the panel entry. Only nl/en exist; there is no third language.
 */

export const MONTHS = {
  nl: ["jan", "feb", "mrt", "apr", "mei", "jun", "jul", "aug", "sep", "okt", "nov", "dec"],
  en: ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"],
};

// Frontend-only translations of the backend's technical enum keys
// (locations/categories/kinds). The backend still sends emoji/icon; only the
// label text is overridden here, per the active language.
export const LOCATION_LABELS = {
  nl: { fridge: "Koelkast", freezer: "Vriezer", pantry: "Buiten koelkast" },
  en: { fridge: "Fridge", freezer: "Freezer", pantry: "Pantry" },
};
export const CATEGORY_LABELS = {
  nl: {
    vegetables: "Groente", fruit: "Fruit", dairy: "Zuivel", meat: "Vlees", fish: "Vis",
    breakfast: "Ontbijt", lunch: "Lunch", dinner: "Avondeten", snack: "Snack",
    bread_bakery: "Brood & bakkerij",
    sauces_spices: "Saus & kruiden", drinks: "Dranken", eggs: "Eieren",
    leftovers: "Restjes", other: "Overig",
  },
  en: {
    vegetables: "Vegetables", fruit: "Fruit", dairy: "Dairy", meat: "Meat", fish: "Fish",
    breakfast: "Breakfast", lunch: "Lunch", dinner: "Dinner", snack: "Snack",
    bread_bakery: "Bakery",
    sauces_spices: "Sauces & spices", drinks: "Drinks", eggs: "Eggs",
    leftovers: "Leftovers", other: "Other",
  },
};
export const KIND_LABELS = {
  nl: {
    ingredient: { label: "Losse ingrediënten", short: "Ingrediënten" },
    dish: { label: "Gerechten", short: "Gerechten" },
  },
  en: {
    ingredient: { label: "Individual ingredients", short: "Ingredients" },
    dish: { label: "Dishes", short: "Dishes" },
  },
};

export const STATUS_COLOR = {
  expired: "var(--fa-red)",
  soon: "var(--fa-orange)",
  ok: "var(--fa-green)",
  none: "var(--fa-muted)",
};

/* ---------------------------------------------------------------- strings */
export const STRINGS = {
  nl: {
    manageLocations: "Locaties beheren",
    locationsHelp: "Voeg aparte koelkasten, vriezers en kasten toe. Het opslagtype bepaalt de houdbaarheidsschattingen.",
    newLocation: "Locatie toevoegen",
    editLocation: "Locatie bewerken",
    storageType: "Opslagtype",
    locationName: "Locatienaam",
    locationNamePlaceholder: "bijv. Vriezer in garage",
    locationEmoji: "Emoji (optioneel)",
    locationArchived: "Gearchiveerd",
    locationArchive: "Archiveren",
    locationRestore: "Actief maken",
    locationRemove: "Locatie verwijderen",
    locationRemoveHelp: "Verplaats alle items voordat je deze locatie verwijdert.",
    locationKeepOne: "Houd minimaal één actieve locatie.",
    locationDateHelp: "Het wijzigen van het opslagtype verandert bestaande houdbaarheidsdatums niet.",
    locationArchivedHelp: "Gearchiveerde locaties blijven bij bestaande items en filters staan, maar zijn niet beschikbaar voor nieuwe of verplaatste items.",
    locationId: "Locatie-ID voor automatiseringen",
    locationSaved: "Locatie opgeslagen",
    locationRemoved: "Locatie verwijderd",
    locationMoveUp: "Omhoog",
    locationMoveDown: "Omlaag",
    useSuggestedExpiry: "Voorgestelde datum gebruiken",
    suggestedExpiry: "Voorgestelde datum",
    keepExpiry: "De bestaande datum blijft staan totdat je deze schatting accepteert.",
    storageFridge: "Koelkast",
    storageFreezer: "Vriezer",
    storagePantry: "Kast",
    locationTypeChanged: "Bestaande houdbaarheidsdatums blijven ongewijzigd.",

    appTitle: "Fridge Assistant",
    appTitleShort: "Fridge",
    historyTooltip: (n) => (n ? `Geschiedenis (${n})` : "Geschiedenis"),
    manageTemplates: "Templates beheren",
    settings: "Instellingen",
    searchPlaceholder: "Zoek…",
    cleanUp: "Opruimen",
    loading: "Laden…",
    scanAria: "Scan barcode",
    addItemAria: "Item toevoegen",

    itemsUnit: "items",
    soonUnit: "bijna op",
    expiredUnit: "over datum",
    all: "Alles",

    emptyTitle: "Nog niets in de koelkast",
    emptySub: "Voeg je eerste item toe — houdbaarheid wordt automatisch geschat.",
    addItemBtn: '<ha-icon icon="mdi:plus"></ha-icon> Item toevoegen',
    useFirst: '<ha-icon icon="mdi:clock-alert-outline"></ha-icon> Als eerste op',
    nothingFound: "Niets gevonden.",
    printSticker: "Print sticker",

    addNamePlaceholder: "Wat leg je erin? bv. krop sla",
    dateInFieldLabel: "Datum erin",
    mealieTitle: "Wat kan ik koken?",
    createTemplateBtn: "Sjabloon maken",
    createdTemplateLinked: "Gekoppeld aan je nieuwe sjabloon",
    removeCategory: "Categorie verwijderen",
    manageCategories: "Categorieën beheren",
    categoriesHelp: "Categorieën ordenen artikelen en sjablonen. Archiveren verbergt een categorie bij nieuwe keuzes en behoudt bestaande artikelen. De standaardsoort geldt voor nieuwe invoer; houdbaarheid blijft in sjablonen.",
    newCategory: "Categorie toevoegen",
    editCategory: "Categorie bewerken",
    categoryName: "Categorienaam",
    categoryDefaultKind: "Standaardsoort",
    categoryEmojiHelp: "Wordt naast de categorie getoond in voorraadfilters en categoriebeheer. Ook gebruikt als standaardemoji voor nieuwe sjablonen.",
    categoryRemoveHelp: "Artikelen en sjablonen worden naar de gekozen categorie verplaatst. Soort en datums blijven gelijk. Archiveer om bestaande toewijzingen te behouden.",
    categoryReplacement: "Vervangende categorie",
    categoryRemoveReassign: "Verwijderen en verplaatsen",
    reorderHandle: name => `${name} verplaatsen. Sleep of gebruik de pijltjestoetsen, Home of End.`,
    reorderPosition: (position,total) => `Positie ${position} van ${total}`,
    noKindCategories: "Voeg een categorie voor deze soort toe via Categorieën beheren",
    automationDetails: "Automatiseringsdetails",
    copyId: "ID kopiëren",
    idCopied: "Locatie-ID gekopieerd",
    copyIdManually: "Selecteer en kopieer de locatie-ID handmatig",
    mappingLinkExisting: "Bestaand sjabloon koppelen",
    mappingSaveLink: "Opslaan en koppelen",
    mappingSaveNext: "Opslaan en volgende",
    mappingTemplateSavedLinkFailed: "Sjabloon opgeslagen, maar koppelen mislukt. Probeer opnieuw om hetzelfde sjabloon te koppelen of koppel het via Bestaand sjabloon koppelen.",
    mappingQueueDone: "Geen ongekoppelde ingrediënten meer in deze weergave.",
    suggestEmoji: "Emoji voorstellen met AI",
    emojiThinking: "Emoji voorstellen…",
    emojiSuggested: "Voorgestelde emoji ingevuld. Je kunt deze wijzigen voordat je opslaat.",
    emojiSuggestionStale: "Naam of emoji gewijzigd; je wijzigingen zijn behouden. Probeer zo nodig opnieuw.",
    emojiSuggestionEmpty: "Geen geschikte emoji ontvangen.",
    emojiSuggestionFailed: "Geen emoji beschikbaar via AI. Kies er zelf een of behoud de standaardemoji van de categorie.",
    inventoryTab: "Voorraad",
    mappingSearch: "Zoek ingrediënten of gekoppelde sjablonen",
    mappingStatus: "Koppelingsstatus",
    mappingReview: "Controleren",
    mappingExact: "Automatisch",
    mappingSaved: "Handmatig gekoppeld",
    mappingAll: "Alle koppelingen",
    mappingScope: "Ingrediënten tonen",
    mappingUsed: "Gebruikt in gesynchroniseerde recepten",
    mappingCatalogue: "Hele Mealie-catalogus",
    mappingPrevious: "Vorige",
    mappingNext: "Volgende",
    mappingResults: "Resultaten",
    mappingUnlinked: "Geen gekoppeld sjabloon",
    mappingChange: "Wijzigen",
    mappingEmpty: "Geen ingrediënten voor deze filters.",
    mappingTemplateSearch: "Zoek Fridge Assistant-sjablonen",
    mappingSaveFailed: "Opslaan mislukt. Probeer opnieuw.",

    recipesTab: "Recepten",
    mealieManage: "Beheren",
    mealieConfigure: "Verbindingsinstellingen",
    mealieUseSoon: "Gebruikt producten die binnenkort op moeten",
    mealiePresence: "Alleen aanwezigheid; controleer hoeveelheden voor het koken.",

    mealiePreview: "Controleert aanwezigheid, geen hoeveelheden. Producten over de uiterste consumptiedatum tellen niet mee. Eerst complete recepten, dan minder ontbrekende ingrediënten, dan producten met een datum binnen drie dagen.",
    mealieNeedsParsing: "Recepten die in Mealie ontleed moeten worden",
    mealieParseHelp: "Deze recepten staan niet in de kookresultaten. Open een recept in Mealie, ontleed de ingrediënten en sla op. Vernieuw daarna hier de recepten.",
    mealieFilter: "Recepten tonen",
    mealieAll: "Alle recepten",
    mealieReady: "Alle ingrediënten aanwezig",
    mealieNear: "1–2 ingrediënten ontbreken",
    mealieMappings: "Mealie-ingrediënten aan sjablonen koppelen",
    mealieMissing: "Ontbrekende ingrediënten",
    mealieReview: "Koppelen of ontleden nodig",
    mealieDays: "dagen tot datum",
    mealiePastBest: "THT verstreken — controleer kwaliteit",
    mealieThaw: "Ontdooien nodig",
    mealieSaved: "Opgeslagen koppeling",
    mealieExact: "Exacte naam of alias",
    mealieAutomatic: "Automatisch koppelen",

    mealieTest: "Verbinding testen",
    mealieSync: "Recepten vernieuwen",
    mealieSearch: "Recepten zoeken",
    mealieSetup: "Vul de Mealie URL en API-token in bij Fridge Assistant-instellingen. De voorraad werkt ook zonder Mealie.",
    mealieWorking: "Verbinden met Mealie\u2026",
    mealieRecipes: "Recepten",
    mealieNever: "Nog niet gesynchroniseerd",
    mealieStale: "Laatste verversing mislukt; opgeslagen recepten getoond",
    mealieIngredients: "ingredi\u00ebnten",
    mealieUnparsed: "moeten worden geparseerd in Mealie",
    mealieOpen: "Openen in Mealie",
    mealieEmpty: "Geen recepten. Configureer Mealie en vernieuw na het importeren.",
    mealieConnected: "Mealie-verbinding geslaagd",
    bestBeforeCheckbox: "Ten minste houdbaar tot-datum",
    useByUnchecked: "Niet aangevinkt betekent Te gebruiken tot.",
    dateTypeLabel: "Datumtype",
    useByLabel: "Te gebruiken tot",
    bestBeforeLabel: "Ten minste houdbaar tot",
    expiryLabel: "Houdbaar tot",
    datePickPlaceholder: "Kies datum",
    dateOptionalPlaceholder: "Optioneel",
    clearDateTitle: "Datum wissen",
    moreOptions: "Meer opties ▾",
    lessOptions: "Minder opties ▴",
    displayNameLabel: "Aparte naam (optioneel)",
    displayNamePlaceholder: "Weergavenaam",
    quantityLabel: "Hoeveelheid",
    quantityPlaceholder: "bv. 2 bakjes",
    emojiLabel: "Emoji",
    notesLabel: "Notitie",
    photoUrlLabel: "Foto-URL (optioneel)",
    photoUrlPlaceholder: "https://…",
    chooseTemplateBtn: '<ha-icon icon="mdi:book-multiple"></ha-icon> Template kiezen',
    saveBtn: "Opslaan",
    addBtn: "Toevoegen",
    aiEstimateMini: '<ha-icon icon="mdi:creation"></ha-icon> AI schat',
    unknownProduct: "Onbekend product",
    noTemplateFor: (q, aiEnabled) =>
      `Nog geen template voor "${q}" — vul zelf een datum in${aiEnabled ? " of laat AI schatten" : ""}.`,
    chooseTemplateTitle: "Kies template",
    notSuitableHere: "Niet geschikt voor deze locatie",
    daysAtLocation: (label, days) => `${label}: ${days} dagen`,
    aiEstimateTitle: "AI-schatting",
    otherTemplateTitle: "Andere template",
    useTemplateNameTitle: "Naam van template overnemen",
    notThisManualTitle: "Niet dit — handmatig",
    manualEntry: "Handmatig invullen",
    savedToast: "Opgeslagen ✓",
    addedToast: (code) => `Toegevoegd ✓ ${code ? "code " + code : ""}`,
    printActionLabel: "Print",
    errorPrefix: "Fout: ",

    aiThinking: "✨ AI denkt na…",
    estimatingFor: (name) => `Houdbaarheid van "${name}" schatten…`,
    aiFailed: "AI-schatting mislukt",
    dayUnitShort: "dg",
    aiHint: "Klopt niet helemaal? Tik een dag-getal aan en pas het aan 👇",
    saveAsTemplateLabel: "Bewaar (met jouw aanpassingen) als template",

    pickTemplateTitle: "Kies een template",
    searchInTemplates: (n) => `Zoek in ${n} templates…`,
    ownSuffix: " · eigen",

    templatesTitle: "Templates",
    templateWithAiTitle: "Template met AI",
    newTemplateTitleIcon: "Nieuwe template",
    hiddenTemplatesTitle: "Verborgen standaard-templates",
    searchOrFilterPlaceholder: "Zoek of filter…",
    nothingHidden: "Niets verborgen.",
    backBtn: '<ha-icon icon="mdi:undo-variant"></ha-icon> Terug',
    restoredToast: "Teruggezet ✓",
    nothingInGroup: "Niets in deze groep.",
    customizedBadge: "aangepast",
    ownBadge: "eigen",

    templateWithAiSub: "Typ een product; AI schat de houdbaarheid, jij past aan.",
    productOrDishLabel: "Product of gerecht",
    productOrDishPlaceholder: "bv. zelfgemaakte curry",
    estimateWithAiBtn: '<ha-icon icon="mdi:creation"></ha-icon> Schat met AI',
    aiErrorPrefix: "AI: ",

    newTemplateHeading: "Nieuwe template",
    editTemplateHeading: "Template bewerken",
    overrideNote: "Aanpassing van standaard-template",
    builtinNote: "Standaard-template — wijziging maakt een eigen versie",
    ownTemplateNote: "Eigen template",
    nameLabel: "Naam",
    namePlaceholderTemplate: "bv. Zelfgemaakte pesto",
    kindLabel: "Soort",
    categoryLabel: "Categorie",
    shelfLifeSectionLabel: "Houdbaarheid in dagen — leeg = niet geschikt",
    notApplicablePlaceholder: "n.v.t.",
    aliasesLabel: "Ook herkennen als (komma-gescheiden)",
    aliasesPlaceholder: "pasta bolognese, spaghetti",
    notesTipLabel: "Notitie / bewaartip",
    notesTipPlaceholder: "Laat afkoelen voor invriezen",
    restoreDefaultBtn: '<ha-icon icon="mdi:restore"></ha-icon> Herstel',
    builtinRemoveBtn: '<ha-icon icon="mdi:eye-off-outline"></ha-icon> Verwijder',
    customRemoveBtn: '<ha-icon icon="mdi:delete-outline"></ha-icon> Verwijder',
    templateAddedToast: "Template toegevoegd ✓",
    templateSavedToast: "Template opgeslagen ✓",
    restoredDefaultToast: "Hersteld naar standaard ✓",
    removedFromListToast: "Uit lijst gehaald ✓",
    templateDeletedToast: "Template verwijderd ✓",

    locationLabel: "Locatie",
    addedByLabel: "Toegevoegd door",
    contentsLabel: "Inhoud",
    dateInDetailLabel: "Erin gelegd",
    daysAgoShort: (n) => `${n} dg geleden`,
    stickerBtn: '<ha-icon icon="mdi:tag-outline"></ha-icon> Sticker',
    editBtn: '<ha-icon icon="mdi:pencil-outline"></ha-icon> Bewerken',
    eatenBtn: '<ha-icon icon="mdi:silverware-fork-knife"></ha-icon> Opgegeten',
    tossedBtn: '<ha-icon icon="mdi:delete-outline"></ha-icon> Weggegooid',

    undoLabel: "Ongedaan",
    completedToast: (emoji, name, eaten) => `${emoji} ${name} ${eaten ? "opgegeten" : "weggegooid"}`,

    notOwnLabel: (val) => `Dit is geen eigen koelkast-label (${val})`,
    noActiveItemWithCode: (val) => `Geen actief item met code ${val}`,
    couldNotEatRetry: "Kon niet opeten — probeer opnieuw",
    eatenStatusCount: (name, n) => `🍽️ ${name} opgegeten (${n})`,

    cleanUpTitle: "Koelkast opruimen",
    expiredSection: "Over datum",
    soonSection: "Bijna over datum",
    allGoodMessage: "Alles is nog goed!",
    removeSelectedBtn: "Verwijder geselecteerde",
    removeNItems: (n) => `Verwijder ${n} item${n === 1 ? "" : "s"}`,
    nothingSelected: "Niets geselecteerd",
    cleanedUpToast: (n) => `🧹 ${n} item${n === 1 ? "" : "s"} opgeruimd`,

    scanTitle: "Scan",
    scanSub: "Je koelkast-label om te zoeken, of een winkelbarcode",
    searchModeBtn: '<ha-icon icon="mdi:magnify"></ha-icon> Zoeken',
    eatModeBtn: '<ha-icon icon="mdi:silverware-fork-knife"></ha-icon> Opeten',
    photoBtn: '<ha-icon icon="mdi:camera"></ha-icon> Foto',
    typeCodeBtn: '<ha-icon icon="mdi:keyboard-outline"></ha-icon> Code typen',
    eatModeStatus: "🍽️ Scan je labels — elk item wordt meteen opgegeten",
    aimAtBarcode: "Richt op de barcode…",
    codeInputPlaceholder: "Code, bv. AB12",
    searchBtn: "Zoek",
    readingPhoto: "Foto lezen…",
    noBarcodeFound: "Geen barcode gevonden — probeer dichterbij en scherp.",
    takePhotoOfBarcode: "Maak een foto van de barcode 📸",
    liveScanUnavailable: "Live scannen kan niet op dit toestel. Typ de code.",
    noCameraAccess: "Geen camera-toegang. Gebruik Foto of Code typen.",
    torchTooltip: "Zaklamp",

    foundToast: (name) => `🔎 ${name} gevonden`,
    noActiveItemHistoryHint: (val) => `Geen actief item met code ${val} — misschien al opgegeten/weggegooid (zie Geschiedenis)`,
    unknownCode: (val) => `Onbekende code: ${val}`,

    lookingUpProduct: (code) => `🔎 Product opzoeken… (${code})`,
    retailBarcodeNote: (code) => `Winkelbarcode ${code}`,
    noProductNameFound: (code) => `Geen productnaam gevonden (${code}) — vul zelf in`,
    recognizedBefore: "🔁 Eerder toegevoegd — herkend",
    productFoundToast: (name) => `🛒 ${name}`,

    justNow: "net",
    minutesAgo: (m) => `${m} min geleden`,
    hoursAgo: (h) => `${h} uur geleden`,
    yesterday: "gisteren",
    daysAgo: (d) => `${d} dagen geleden`,

    restoreToFridgeTitle: "Terugzetten in de koelkast",
    historyHeading: "Geschiedenis",
    loadMoreBtn: "Meer laden",
    historyLoadFailed: "Kon geschiedenis niet laden.",
    historyEmpty: "Nog niets opgegeten of weggegooid.",
    historySummary: (total) => `${total} afgerond${total >= 500 ? " (laatste 500)" : ""}`,
    restoreFailedToast: "Herstellen mislukt",
    restoredToFridgeToast: "↩︎ Teruggezet in de koelkast",
    deleteEventTitle: "Definitief verwijderen",
    confirmDeleteLabel: "Zeker?",
    eventDeletedToast: "Definitief verwijderd",
    deleteFailedToast: "Verwijderen mislukt",

    printerLiveNote: (name, size, copies) =>
      `Print via <b>${name}</b> op ${size}-labels${copies > 1 ? ` · ${copies}× per keer` : ""}. Voorbeeld = werkelijke labelmaat.`,
    printerSearching: "Printers zoeken…",
    printerInviteNote: (url) =>
      `Zin om dit als échte sticker te printen? Met de <a href="${url}" target="_blank" rel="noreferrer">Label Printer add-on</a> en een DYMO- of Zebra-labelprinter rolt dit voorbeeld er zo uit. Daarna printen aanzetten bij de instellingen.`,
    printerAddonDownNote: (url) =>
      `De Label Printer add-on is niet bereikbaar op <code>${url}</code>. Draait de add-on?`,
    printerNoPrintersNote:
      "Er zijn geen labelprinters beschikbaar. Controleer of je printer aan staat en bereikbaar is.",
    printStickerModalTitle: "Sticker printen",
    previewLoading: "Voorbeeld laden…",
    closeBtn: "Sluiten",
    showAll: "Toon alles",
    retryBtn: "Opnieuw proberen",
    subscribeErrorTitle: "Geen verbinding met Fridge Assistant",
    subscribeErrorSub: "De integratie reageert niet. Draait Home Assistant nog op de achtergrond?",
    printBatchStopped: (n, total) => `Printen gestopt na ${n}/${total} stickers.`,
    historyBtnLabel: "Geschiedenis",
    actionFailed: (err) => `Mislukt: ${err}`,
    printBtnLabel: (copies) => `<ha-icon icon="mdi:printer"></ha-icon> Print${copies > 1 ? ` (${copies}×)` : ""}`,
    previewUnavailable: (err) => `Voorbeeld niet beschikbaar: ${err}`,
    workingLabel: "Bezig…",
    stickerPrintedToast: (code, copies) => `🖨️ Sticker ${code} geprint${copies > 1 ? ` (${copies}×)` : ""}`,
    printerDisabledReason: "Printer staat uit — zet 'm aan bij de instellingen.",
    printerUnreachableReason: "Label Printer add-on niet bereikbaar. Staat de add-on aan?",
    printerNotConnectedReason: "De DYMO is niet gevonden. Check kabel/stroom en herstart de add-on.",
    renderFailedReason: "Label renderen mislukte.",
    genericPrintFailed: (reason) => `Printen mislukte (${reason || "?"})`,
    printFailedError: (err) => `Print mislukt: ${err}`,

    portionsLabel: "Porties",
    portionsFieldNote: "Elke portie krijgt een eigen stickercode (bv. AB12-1)",
    portionsStepperNote: "Zo is de batch verdeeld · − haalt een ongebruikte portie weg",
    portionRowLabel: (n) => `Portie ${n}`,
    portionOpenLabel: "open",
    eatPortionTitle: "Deze portie opeten",
    tossPortionTitle: "Deze portie weggooien",
    printPortionTitle: "Sticker voor deze portie printen",
    undoPortionTitle: "Portie terugzetten",
    portionEatenToast: (name, n, total, remaining) =>
      `🍽️ Portie ${n}/${total} van ${name} · nog ${remaining} over`,
    portionTossedToast: (name, n, total, remaining) =>
      `🗑️ Portie ${n}/${total} van ${name} · nog ${remaining} over`,
    portionNotFoundMsg: (val) => `Portie ${val} bestaat niet (meer)`,
    portionConsumedMsg: (val) => `Portie ${val} is al opgegeten of weggegooid`,
    noOpenPortionsMsg: "Geen open porties meer",
    openItemLabel: "Open item",
    printAllStickersBtn: (n) => `<ha-icon icon="mdi:printer"></ha-icon> Print ${n} stickers`,
    printingProgress: (i, n) => `Printen… ${i}/${n}`,
    printedStickersToast: (n, code) => `🖨️ ${n} stickers ${code} geprint`,
    pbadgeTitle: (open, total) => `${open} van ${total} porties over`,
    histPortionLabel: (n, total) => `Portie ${n}${total ? `/${total}` : ""}`,
    portionAddedToast: (n) => `Portie ${n} toegevoegd`,

    secThisWeek: "Deze week",
    secLater: "Later",
    secNoDate: "Zonder datum",
  },

  en: {
    manageLocations: "Manage locations",
    locationsHelp: "Add separate fridges, freezers and cupboards. The storage type determines shelf-life estimates.",
    newLocation: "Add location",
    editLocation: "Edit location",
    storageType: "Storage type",
    locationName: "Location name",
    locationNamePlaceholder: "e.g. Garage freezer",
    locationEmoji: "Emoji (optional)",
    locationArchived: "Archived",
    locationArchive: "Archive",
    locationRestore: "Make active",
    locationRemove: "Remove location",
    locationRemoveHelp: "Move all items elsewhere before removing this location.",
    locationKeepOne: "Keep at least one active location.",
    locationDateHelp: "Changing the storage type leaves existing expiry dates unchanged.",
    locationArchivedHelp: "Archived locations stay on existing items and filters, but cannot be selected for new or moved items.",
    locationId: "Location ID for automations",
    locationSaved: "Location saved",
    locationRemoved: "Location removed",
    locationMoveUp: "Move up",
    locationMoveDown: "Move down",
    useSuggestedExpiry: "Use suggested expiry",
    suggestedExpiry: "Suggested expiry",
    keepExpiry: "The existing date is kept unless you accept this estimate.",
    storageFridge: "Fridge",
    storageFreezer: "Freezer",
    storagePantry: "Cupboard",
    locationTypeChanged: "Existing expiry dates are unchanged.",

    appTitle: "Fridge Assistant",
    appTitleShort: "Fridge",
    historyTooltip: (n) => (n ? `History (${n})` : "History"),
    manageTemplates: "Manage templates",
    settings: "Settings",
    searchPlaceholder: "Search…",
    cleanUp: "Clean up",
    loading: "Loading…",
    scanAria: "Scan barcode",
    addItemAria: "Add item",

    itemsUnit: "items",
    soonUnit: "soon",
    expiredUnit: "past date",
    all: "All",

    emptyTitle: "Nothing in the fridge yet",
    emptySub: "Add your first item — expiry is estimated automatically.",
    addItemBtn: '<ha-icon icon="mdi:plus"></ha-icon> Add item',
    useFirst: '<ha-icon icon="mdi:clock-alert-outline"></ha-icon> Use first',
    nothingFound: "Nothing found.",
    printSticker: "Print sticker",

    addNamePlaceholder: "What are you putting in? e.g. lettuce",
    dateInFieldLabel: "Date added",
    mealieTitle: "What can I cook?",
    createTemplateBtn: "Create template",
    createdTemplateLinked: "Linked to your new template",
    removeCategory: "Remove category",
    manageCategories: "Manage categories",
    categoriesHelp: "Categories organise items and templates. Archiving hides a category from new selections while keeping existing items. Default kind applies to new entries; shelf life stays in templates.",
    newCategory: "Add category",
    editCategory: "Edit category",
    categoryName: "Category name",
    categoryDefaultKind: "Default kind",
    categoryEmojiHelp: "Shown beside the category in inventory filters and category management. Also used as the default emoji for new templates.",
    categoryRemoveHelp: "Items and templates in this category will move to the selected replacement. Their kind and dates stay the same. Archive instead if you want to keep existing assignments.",
    categoryReplacement: "Replacement category",
    categoryRemoveReassign: "Remove and reassign",
    reorderHandle: name => `Reorder ${name}. Drag, or use arrow keys, Home or End.`,
    reorderPosition: (position,total) => `Position ${position} of ${total}`,
    noKindCategories: "Add a category for this kind in Manage categories",
    automationDetails: "Automation details",
    copyId: "Copy ID",
    idCopied: "Location ID copied",
    copyIdManually: "Select and copy the location ID manually",
    mappingLinkExisting: "Link existing",
    mappingSaveLink: "Save and link",
    mappingSaveNext: "Save and next",
    mappingTemplateSavedLinkFailed: "Template saved, but linking failed. Retry to link the same template, or close and link it using Link existing.",
    mappingQueueDone: "No more unmatched ingredients in this view.",
    suggestEmoji: "Suggest emoji with AI",
    emojiThinking: "Suggesting an emoji…",
    emojiSuggested: "Suggested emoji applied. You can change it before saving.",
    emojiSuggestionStale: "Name or emoji changed; your edits have been kept. Try again if needed.",
    emojiSuggestionEmpty: "No suitable emoji was returned.",
    emojiSuggestionFailed: "Could not suggest an emoji. Choose one manually or keep the category default.",
    inventoryTab: "Inventory",
    mappingSearch: "Search ingredients or linked templates",
    mappingStatus: "Mapping status",
    mappingReview: "Needs review",
    mappingExact: "Automatic",
    mappingSaved: "Manually linked",
    mappingAll: "All mappings",
    mappingScope: "Ingredients to show",
    mappingUsed: "Used by synced recipes",
    mappingCatalogue: "Whole Mealie food catalogue",
    mappingPrevious: "Previous",
    mappingNext: "Next",
    mappingResults: "Results",
    mappingUnlinked: "No linked template",
    mappingChange: "Change",
    mappingEmpty: "No ingredients match these filters.",
    mappingTemplateSearch: "Search Fridge Assistant templates",
    mappingSaveFailed: "Could not save. Please try again.",

    recipesTab: "Recipes",
    mealieManage: "Manage",
    mealieConfigure: "Connection settings",
    mealieUseSoon: "Uses food due soon",
    mealiePresence: "Ingredient presence only; check quantities before cooking.",

    mealiePreview: "Checks ingredient presence, not sufficient quantities. Past Use By stock is excluded. Recipes with all ingredients come first, then fewer missing or unresolved ingredients, then those using food due within three days.",
    mealieNeedsParsing: "Recipes needing parsing in Mealie",
    mealieParseHelp: "These recipes are hidden from cooking results. Open a recipe in Mealie, parse its ingredients and save, then refresh recipes here.",
    mealieFilter: "Show recipes",
    mealieAll: "All recipes",
    mealieReady: "All ingredients present",
    mealieNear: "Missing 1–2 ingredients",
    mealieMappings: "Link Mealie foods to templates",
    mealieMissing: "Missing ingredients",
    mealieReview: "Needs matching or parsing",
    mealieDays: "days until date",
    mealiePastBest: "Past Best Before — check quality",
    mealieThaw: "Needs thawing",
    mealieSaved: "Saved mapping",
    mealieExact: "Exact name or alias match",
    mealieAutomatic: "Automatic matching",

    mealieTest: "Test connection",
    mealieSync: "Refresh recipes",
    mealieSearch: "Search recipes",
    mealieSetup: "Enter the Mealie URL and API token in Fridge Assistant settings. Inventory works without Mealie.",
    mealieWorking: "Connecting to Mealie\u2026",
    mealieRecipes: "Recipes",
    mealieNever: "Not synchronised yet",
    mealieStale: "Last refresh failed; showing saved recipes",
    mealieIngredients: "ingredients",
    mealieUnparsed: "need ingredient parsing in Mealie",
    mealieOpen: "Open in Mealie",
    mealieEmpty: "No recipes to show. Configure Mealie and refresh after importing recipes.",
    mealieConnected: "Mealie connection successful",
    bestBeforeCheckbox: "Best Before date",
    useByUnchecked: "Unticked means Use By.",
    dateTypeLabel: "Date type",
    useByLabel: "Use By",
    bestBeforeLabel: "Best Before",
    expiryLabel: "Use by",
    datePickPlaceholder: "Pick a date",
    dateOptionalPlaceholder: "Optional",
    clearDateTitle: "Clear date",
    moreOptions: "More options ▾",
    lessOptions: "Fewer options ▴",
    displayNameLabel: "Custom name (optional)",
    displayNamePlaceholder: "Display name",
    quantityLabel: "Quantity",
    quantityPlaceholder: "e.g. 2 containers",
    emojiLabel: "Emoji",
    notesLabel: "Note",
    photoUrlLabel: "Photo URL (optional)",
    photoUrlPlaceholder: "https://…",
    chooseTemplateBtn: '<ha-icon icon="mdi:book-multiple"></ha-icon> Choose template',
    saveBtn: "Save",
    addBtn: "Add",
    aiEstimateMini: '<ha-icon icon="mdi:creation"></ha-icon> AI estimate',
    unknownProduct: "Unknown product",
    noTemplateFor: (q, aiEnabled) =>
      `No template yet for "${q}" — enter a date yourself${aiEnabled ? " or let AI estimate" : ""}.`,
    chooseTemplateTitle: "Choose template",
    notSuitableHere: "Not suitable for this location",
    daysAtLocation: (label, days) => `${label}: ${days} days`,
    aiEstimateTitle: "AI estimate",
    otherTemplateTitle: "Different template",
    useTemplateNameTitle: "Use the template's name",
    notThisManualTitle: "Not this — manual",
    manualEntry: "Manual entry",
    savedToast: "Saved ✓",
    addedToast: (code) => `Added ✓ ${code ? "code " + code : ""}`,
    printActionLabel: "Print",
    errorPrefix: "Error: ",

    aiThinking: "✨ AI is thinking…",
    estimatingFor: (name) => `Estimating shelf life for "${name}"…`,
    aiFailed: "AI estimate failed",
    dayUnitShort: "d",
    aiHint: "Not quite right? Tap a day count to adjust it 👇",
    saveAsTemplateLabel: "Save (with your edits) as a template",

    pickTemplateTitle: "Choose a template",
    searchInTemplates: (n) => `Search ${n} templates…`,
    ownSuffix: " · custom",

    templatesTitle: "Templates",
    templateWithAiTitle: "Template with AI",
    newTemplateTitleIcon: "New template",
    hiddenTemplatesTitle: "Hidden built-in templates",
    searchOrFilterPlaceholder: "Search or filter…",
    nothingHidden: "Nothing hidden.",
    backBtn: '<ha-icon icon="mdi:undo-variant"></ha-icon> Back',
    restoredToast: "Restored ✓",
    nothingInGroup: "Nothing in this group.",
    customizedBadge: "customized",
    ownBadge: "custom",

    templateWithAiSub: "Type a product; AI estimates shelf life, you adjust it.",
    productOrDishLabel: "Product or dish",
    productOrDishPlaceholder: "e.g. homemade curry",
    estimateWithAiBtn: '<ha-icon icon="mdi:creation"></ha-icon> Estimate with AI',
    aiErrorPrefix: "AI: ",

    newTemplateHeading: "New template",
    editTemplateHeading: "Edit template",
    overrideNote: "Customization of a built-in template",
    builtinNote: "Built-in template — editing creates your own version",
    ownTemplateNote: "Your own template",
    nameLabel: "Name",
    namePlaceholderTemplate: "e.g. Homemade pesto",
    kindLabel: "Kind",
    categoryLabel: "Category",
    shelfLifeSectionLabel: "Shelf life in days — empty = not suitable",
    notApplicablePlaceholder: "n/a",
    aliasesLabel: "Also recognize as (comma-separated)",
    aliasesPlaceholder: "pasta bolognese, spaghetti",
    notesTipLabel: "Note / storage tip",
    notesTipPlaceholder: "Let cool before freezing",
    restoreDefaultBtn: '<ha-icon icon="mdi:restore"></ha-icon> Restore',
    builtinRemoveBtn: '<ha-icon icon="mdi:eye-off-outline"></ha-icon> Remove',
    customRemoveBtn: '<ha-icon icon="mdi:delete-outline"></ha-icon> Remove',
    templateAddedToast: "Template added ✓",
    templateSavedToast: "Template saved ✓",
    restoredDefaultToast: "Restored to default ✓",
    removedFromListToast: "Removed from list ✓",
    templateDeletedToast: "Template deleted ✓",

    locationLabel: "Location",
    addedByLabel: "Added by",
    contentsLabel: "Contents",
    dateInDetailLabel: "Added on",
    daysAgoShort: (n) => `${n}d ago`,
    stickerBtn: '<ha-icon icon="mdi:tag-outline"></ha-icon> Sticker',
    editBtn: '<ha-icon icon="mdi:pencil-outline"></ha-icon> Edit',
    eatenBtn: '<ha-icon icon="mdi:silverware-fork-knife"></ha-icon> Eaten',
    tossedBtn: '<ha-icon icon="mdi:delete-outline"></ha-icon> Tossed',

    undoLabel: "Undo",
    completedToast: (emoji, name, eaten) => `${emoji} ${name} ${eaten ? "eaten" : "tossed"}`,

    notOwnLabel: (val) => `This isn't one of your own fridge labels (${val})`,
    noActiveItemWithCode: (val) => `No active item with code ${val}`,
    couldNotEatRetry: "Couldn't mark as eaten — try again",
    eatenStatusCount: (name, n) => `🍽️ ${name} eaten (${n})`,

    cleanUpTitle: "Clean up the fridge",
    expiredSection: "Past date",
    soonSection: "Expiring soon",
    allGoodMessage: "Everything is still good!",
    removeSelectedBtn: "Remove selected",
    removeNItems: (n) => `Remove ${n} item${n === 1 ? "" : "s"}`,
    nothingSelected: "Nothing selected",
    cleanedUpToast: (n) => `🧹 ${n} item${n === 1 ? "" : "s"} cleaned up`,

    scanTitle: "Scan",
    scanSub: "Your fridge label to search, or a retail barcode",
    searchModeBtn: '<ha-icon icon="mdi:magnify"></ha-icon> Search',
    eatModeBtn: '<ha-icon icon="mdi:silverware-fork-knife"></ha-icon> Eat',
    photoBtn: '<ha-icon icon="mdi:camera"></ha-icon> Photo',
    typeCodeBtn: '<ha-icon icon="mdi:keyboard-outline"></ha-icon> Type code',
    eatModeStatus: "🍽️ Scan your labels — each item is marked eaten right away",
    aimAtBarcode: "Point at the barcode…",
    codeInputPlaceholder: "Code, e.g. AB12",
    searchBtn: "Search",
    readingPhoto: "Reading photo…",
    noBarcodeFound: "No barcode found — try closer and in focus.",
    takePhotoOfBarcode: "Take a photo of the barcode 📸",
    liveScanUnavailable: "Live scanning isn't available on this device. Type the code.",
    noCameraAccess: "No camera access. Use Photo or Type code.",
    torchTooltip: "Flashlight",

    foundToast: (name) => `🔎 ${name} found`,
    noActiveItemHistoryHint: (val) => `No active item with code ${val} — maybe already eaten/tossed (see History)`,
    unknownCode: (val) => `Unknown code: ${val}`,

    lookingUpProduct: (code) => `🔎 Looking up product… (${code})`,
    retailBarcodeNote: (code) => `Retail barcode ${code}`,
    noProductNameFound: (code) => `No product name found (${code}) — fill it in yourself`,
    recognizedBefore: "🔁 Added before — recognized",
    productFoundToast: (name) => `🛒 ${name}`,

    justNow: "just now",
    minutesAgo: (m) => `${m} min ago`,
    hoursAgo: (h) => `${h} hour${h === 1 ? "" : "s"} ago`,
    yesterday: "yesterday",
    daysAgo: (d) => `${d} days ago`,

    restoreToFridgeTitle: "Put back in the fridge",
    historyHeading: "History",
    loadMoreBtn: "Load more",
    historyLoadFailed: "Couldn't load history.",
    historyEmpty: "Nothing eaten or tossed yet.",
    historySummary: (total) => `${total} completed${total >= 500 ? " (last 500)" : ""}`,
    restoreFailedToast: "Restore failed",
    restoredToFridgeToast: "↩︎ Put back in the fridge",
    deleteEventTitle: "Delete permanently",
    confirmDeleteLabel: "Sure?",
    eventDeletedToast: "Deleted permanently",
    deleteFailedToast: "Delete failed",

    printerLiveNote: (name, size, copies) =>
      `Prints via <b>${name}</b> on ${size} labels${copies > 1 ? ` · ${copies}× per tap` : ""}. Preview = actual label size.`,
    printerSearching: "Looking for printers…",
    printerInviteNote: (url) =>
      `Want this as a real sticker? With the <a href="${url}" target="_blank" rel="noreferrer">Label Printer add-on</a> and a DYMO or Zebra label printer this preview rolls right out. Then enable printing in the settings.`,
    printerAddonDownNote: (url) =>
      `The Label Printer add-on is unreachable at <code>${url}</code>. Is it running?`,
    printerNoPrintersNote:
      "No label printers are available. Check that your printer is powered on and reachable.",
    printStickerModalTitle: "Print sticker",
    previewLoading: "Loading preview…",
    closeBtn: "Close",
    showAll: "Show all",
    retryBtn: "Try again",
    subscribeErrorTitle: "No connection to Fridge Assistant",
    subscribeErrorSub: "The integration is not responding. Is Home Assistant still running in the background?",
    printBatchStopped: (n, total) => `Printing stopped after ${n}/${total} stickers.`,
    historyBtnLabel: "History",
    actionFailed: (err) => `Failed: ${err}`,
    printBtnLabel: (copies) => `<ha-icon icon="mdi:printer"></ha-icon> Print${copies > 1 ? ` (${copies}×)` : ""}`,
    previewUnavailable: (err) => `Preview unavailable: ${err}`,
    workingLabel: "Working…",
    stickerPrintedToast: (code, copies) => `🖨️ Sticker ${code} printed${copies > 1 ? ` (${copies}×)` : ""}`,
    printerDisabledReason: "Printer is off — enable it in the settings.",
    printerUnreachableReason: "Label Printer add-on unreachable. Is the add-on running?",
    printerNotConnectedReason: "The DYMO wasn't found. Check cable/power and restart the add-on.",
    renderFailedReason: "Rendering the label failed.",
    genericPrintFailed: (reason) => `Printing failed (${reason || "?"})`,
    printFailedError: (err) => `Print failed: ${err}`,

    portionsLabel: "Portions",
    portionsFieldNote: "Each portion gets its own sticker code (e.g. AB12-1)",
    portionsStepperNote: "How the batch is split · − removes an unused portion",
    portionRowLabel: (n) => `Portion ${n}`,
    portionOpenLabel: "open",
    eatPortionTitle: "Eat this portion",
    tossPortionTitle: "Toss this portion",
    printPortionTitle: "Print this portion's sticker",
    undoPortionTitle: "Put portion back",
    portionEatenToast: (name, n, total, remaining) =>
      `🍽️ Portion ${n}/${total} of ${name} · ${remaining} left`,
    portionTossedToast: (name, n, total, remaining) =>
      `🗑️ Portion ${n}/${total} of ${name} · ${remaining} left`,
    portionNotFoundMsg: (val) => `Portion ${val} does not exist (anymore)`,
    portionConsumedMsg: (val) => `Portion ${val} was already eaten or tossed`,
    noOpenPortionsMsg: "No open portions left",
    openItemLabel: "Open item",
    printAllStickersBtn: (n) => `<ha-icon icon="mdi:printer"></ha-icon> Print ${n} stickers`,
    printingProgress: (i, n) => `Printing… ${i}/${n}`,
    printedStickersToast: (n, code) => `🖨️ ${n} stickers ${code} printed`,
    pbadgeTitle: (open, total) => `${open} of ${total} portions left`,
    histPortionLabel: (n, total) => `Portion ${n}${total ? `/${total}` : ""}`,
    portionAddedToast: (n) => `Portion ${n} added`,

    secThisWeek: "This week",
    secLater: "Later",
    secNoDate: "No date",
  },
};
